USE [CSDLPT_Site2];
GO

CREATE TABLE Lop (
    MaLop VARCHAR(10) PRIMARY KEY,
    TenLop NVARCHAR(50) NOT NULL,
    Khoa NVARCHAR(50)
);
GO

CREATE TABLE SinhVien (
    MaSV VARCHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    Phai NVARCHAR(10),
    NgaySinh DATE,
    MaLop VARCHAR(10) FOREIGN KEY REFERENCES Lop(MaLop),
    HocBong MONEY
);
GO

CREATE TABLE DangKy (
    MaSV VARCHAR(10) FOREIGN KEY REFERENCES SinhVien(MaSV),
    MaMon VARCHAR(10),
    Diem1 DECIMAL(4,2),
    Diem2 DECIMAL(4,2),
    Diem3 DECIMAL(4,2),
    PRIMARY KEY (MaSV, MaMon)
);
GO